version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    depends_on:
      - postgres
      - pghero
      - redis
      - pgadmin
  postgres:
    container_name: ts-docker
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  pghero:
    container_name: task-dock
    image: ankane/pghero
    ports:
    - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/postgres
  redis:
    image: redis
    ports:
    - "6379:6379"